### ISSUE TITLE
enquire

### ISSUE THREAD

**Issue by Oadedoy** [moufidayoub11/betty-extension#1]
how do I install Betty style checker extension?

**Comment by moufidayoub11** [comment]
You can do it in many ways but here is the easiest one:

- Open vs code
- Go to the extensions bar
- Search for **"Betty"**
- Click install

and that's it

**Comment by Oadedoy** [comment]
I have...it's requirement is I should install a Betty style checker and
configure it in my system...I am asking about how to go about that

**Comment by moufidayoub11** [comment]
Ah ok take this command it will do:
`git clone https://github.com/alx-tools/Betty.git && cd Betty && sudo ./install.sh`
